customhost = "employee.cg8ivh7zshcz.ap-south-1.rds.amazonaws.com"
customuser = "venkat"
custompass = "12021m110"
customdb = "employee"
custombucket = "employee-database-aws"
customregion = "ap-south-1"
